In [1]:
import pandas as pd

In [2]:
data = {('California', 2000): 33871648,
 ('California', 2010): 37253956,
 ('Texas', 2000): 20851820,
 ('Texas', 2010): 25145561,
 ('New York', 2000): 18976457,
 ('New York', 2010): 19378102}

In [3]:
data

{('California', 2000): 33871648,
 ('California', 2010): 37253956,
 ('Texas', 2000): 20851820,
 ('Texas', 2010): 25145561,
 ('New York', 2000): 18976457,
 ('New York', 2010): 19378102}

In [5]:
data['California',2000]

33871648

In [7]:
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [9]:
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [10]:
data

{('California', 2000): 33871648,
 ('California', 2010): 37253956,
 ('Texas', 2000): 20851820,
 ('Texas', 2010): 25145561,
 ('New York', 2000): 18976457,
 ('New York', 2010): 19378102}

In [11]:
data_pandas=pd.Series(data)

In [12]:
data_pandas

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [16]:
data_pandas['California'][2010]

37253956

In [22]:
data_pandas.columns=["Negara","Tahun","Populasi"]

In [19]:
data_pandas.column

['Negara', 'Tahun', 'Populasi']

In [26]:
print(data_pandas)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64


In [30]:
data_pandas.index.names = ['state', 'year']

In [28]:
print(data_pandas)

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64


In [31]:
data_pandas.unstack()

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [40]:
B = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
 columns=list('BAC'))

In [33]:
import numpy as np

In [42]:
rng = np.random

In [41]:
B

B  A  C
0  5  9  1
1  0  9  8
2  2  5  8

In [43]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
 columns=list('AB'))

In [44]:
A

A   B
0   5   9
1  16  10

In [45]:
B-A

A     B   C
0  4.0  -4.0 NaN
1 -7.0 -10.0 NaN
2  NaN   NaN NaN

In [46]:
A.stack()

0  A     5
   B     9
1  A    16
   B    10
dtype: int32

In [47]:
A

A   B
0   5   9
1  16  10

In [49]:
fill=A.stack().mean()

In [58]:
A.stack().mean()

10.0

In [51]:
A.add(B, fill_value=fill)

A     B     C
0  14.0  14.0  11.0
1  25.0  10.0  18.0
2  15.0  12.0  18.0

In [52]:
B

A   B
0   5   9
1  16  10

AttributeError: 'DataFrame' object has no attribute 'sort'

In [56]:
B.sort_index()

B  A  C
0  5  9  1
1  0  9  8
2  2  5  8

In [59]:
A.fill_value=fill

In [60]:
A1=A.fill_value=fill

In [61]:
A1

10.0

In [62]:
A

A   B
0   5   9
1  16  10

In [63]:
A.add(B,fill_value=fill)

A     B     C
0  14.0  14.0  11.0
1  25.0  10.0  18.0
2  15.0  12.0  18.0

AttributeError: 'DataFrame' object has no attribute 'addB'

In [67]:
A = rng.randint(10, size=(3, 4))

In [68]:
A

array([[3, 1, 2, 5],
       [7, 8, 2, 8],
       [2, 9, 1, 3]])

In [69]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 4,  7,  0,  3],
       [-1,  8, -1, -2]])

In [70]:
A

array([[3, 1, 2, 5],
       [7, 8, 2, 8],
       [2, 9, 1, 3]])

In [75]:
df = pd.DataFrame(A, columns=list('QRST'))

In [72]:
df

Q  R  S  T
0  3  1  2  5
1  7  8  2  8
2  2  9  1  3

In [79]:
df.columns=list('QRST')

In [87]:
df-df.loc[)]

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (2642266489.py, line 1)

In [88]:
 data = pd.Series([1, np.nan, 'hello', None])

In [89]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [91]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [92]:
data.isnull().sum()

2

In [93]:
data.dropna()

0        1
2    hello
dtype: object

In [94]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [95]:
df = pd.DataFrame([[1, np.nan, 2],
 [2, 3, 5],
 [np.nan, 4, 6]])

In [96]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [100]:
df.isnull()

0      1      2
0  False   True  False
1  False  False  False
2   True  False  False

In [102]:
df[3]=np.nan

In [103]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [105]:
df.dropna(axis='columns',how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [106]:
 data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
 data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [107]:
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [110]:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [111]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
 names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
 names=['subject', 'type'])


In [112]:
index

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])

In [115]:
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data+=37

In [116]:
data

array([[40. , 35.8, 27. , 37.4, 31. , 36.2],
       [32. , 37.6, 25. , 36.2, 26. , 39.7],
       [33. , 37.1, 49. , 37.8, 32. , 35.5],
       [39. , 37.1, 52. , 36. , 55. , 35.9]])

In [117]:
health_data = pd.DataFrame(data, index=index, columns=columns)

In [120]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      40.0  35.8  27.0  37.4  31.0  36.2
     2      32.0  37.6  25.0  36.2  26.0  39.7
2014 1      33.0  37.1  49.0  37.8  32.0  35.5
     2      39.0  37.1  52.0  36.0  55.0  35.9

In [128]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      27.0  37.4
     2      25.0  36.2
2014 1      49.0  37.8
     2      52.0  36.0

In [129]:
import pandas as pd

In [130]:
pokemon=pd.read_csv('pokemon.csv')

In [147]:
pokemon.iloc[0,1]

'Bulbasaur'

In [148]:
data

array([[40. , 35.8, 27. , 37.4, 31. , 36.2],
       [32. , 37.6, 25. , 36.2, 26. , 39.7],
       [33. , 37.1, 49. , 37.8, 32. , 35.5],
       [39. , 37.1, 52. , 36. , 55. , 35.9]])

In [155]:
health_data.iloc[0:2]

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      40.0  35.8  27.0  37.4  31.0  36.2
     2      32.0  37.6  25.0  36.2  26.0  39.7

In [161]:
health_data[health_data>40].count()

subject  type
Bob      HR      0
         Temp    0
Guido    HR      2
         Temp    0
Sue      HR      1
         Temp    0
dtype: int64

In [162]:
health_data['Guido','HR']

year  visit
2013  1        27.0
      2        25.0
2014  1        49.0
      2        52.0
Name: (Guido, HR), dtype: float64

In [164]:
health_data.iloc[:3, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      40.0  35.8
     2      32.0  37.6
2014 1      33.0  37.1

In [167]:
idx = pd.IndexSlice

In [168]:
idx

In [170]:
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      40.0  27.0  31.0
2014 1      33.0  49.0  32.0

In [172]:
health_data.unstack()

subject   Bob                   Guido                     Sue              \
type       HR        Temp          HR        Temp          HR        Temp   
visit       1     2     1     2     1     2     1     2     1     2     1   
year                                                                        
2013     40.0  32.0  35.8  37.6  27.0  25.0  37.4  36.2  31.0  26.0  36.2   
2014     33.0  39.0  37.1  37.1  49.0  52.0  37.8  36.0  32.0  55.0  35.5   

subject        
type           
visit       2  
year           
2013     39.7  
2014     35.9

In [173]:
health_data.sort_index()

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      40.0  35.8  27.0  37.4  31.0  36.2
     2      32.0  37.6  25.0  36.2  26.0  39.7
2014 1      33.0  37.1  49.0  37.8  32.0  35.5
     2      39.0  37.1  52.0  36.0  55.0  35.9

In [174]:
 index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
 data = pd.Series(np.random.rand(6), index=index)
 data.index.names = ['char', 'int']
 data

char  int
a     1      0.781368
      2      0.462466
c     1      0.982006
      2      0.925058
b     1      0.646734
      2      0.407382
dtype: float64

In [175]:
data.sort_index()

char  int
a     1      0.781368
      2      0.462466
b     1      0.646734
      2      0.407382
c     1      0.982006
      2      0.925058
dtype: float64

In [178]:
data['a':'b']

UnsortedIndexError: 'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [179]:
data

char  int
a     1      0.781368
      2      0.462466
c     1      0.982006
      2      0.925058
b     1      0.646734
      2      0.407382
dtype: float64

In [180]:
new_data=data.sort_index()

In [183]:
data.index.name=['name','apa']

TypeError: MultiIndex.name must be a hashable type

In [184]:
data

char  int
a     1      0.781368
      2      0.462466
c     1      0.982006
      2      0.925058
b     1      0.646734
      2      0.407382
dtype: float64

In [186]:
 data.index.names = ['ant', 'int']

In [189]:
data.index.names=['name','apa']

In [191]:
data_mean = health_data.mean(level='year')
data_mean

C:\Users\ASUS\AppData\Local\Temp\ipykernel_6796\2845460446.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  data_mean = health_data.mean(level='year')


subject   Bob       Guido         Sue       
type       HR  Temp    HR  Temp    HR   Temp
year                                        
2013     36.0  36.7  26.0  36.8  28.5  37.95
2014     36.0  37.1  50.5  36.9  43.5  35.70

In [192]:
df1 = make_df('AB', [1, 2])

NameError: name 'make_df' is not defined

In [193]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
 'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
 'hire_date': [2004, 2008, 2012, 2014]})

In [197]:
print(df1)
print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [198]:
 df3 = pd.merge(df1, df2)


In [199]:
print(df3)

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


In [200]:
 df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
 'food': ['fish', 'beans', 'bread']},
 columns=['name', 'food'])
 df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
 'drink': ['wine', 'beer']},
 columns=['name', 'drink'])


In [207]:
pd.merge(df6,df7,on='food',how='right')

KeyError: 'food'

In [205]:
data

name  apa
a     1      0.781368
      2      0.462466
c     1      0.982006
      2      0.925058
b     1      0.646734
      2      0.407382
dtype: float64

In [206]:
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [208]:
 pop = pd.read_csv('state-population.csv')
 areas = pd.read_csv('state-areas.csv')
 abbrevs = pd.read_csv('state-abbrevs.csv')

In [215]:
pop.head()

state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [213]:
areas.head()

state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [214]:
abbrevs.head()

state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [218]:
gabungan=pd.merge(pop,abbrevs,how='outer')

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [222]:
merged=pd.merge(pop,abbrevs how='outer',
 left_on='state/region', right_on='abbreviation')


SyntaxError: invalid syntax (2855958634.py, line 1)

In [225]:
merged.drop('abbreviation',axis=1)

state/region     ages  year   population    state
0              AL  under18  2012    1117489.0  Alabama
1              AL    total  2012    4817528.0  Alabama
2              AL  under18  2010    1130966.0  Alabama
3              AL    total  2010    4785570.0  Alabama
4              AL  under18  2011    1125763.0  Alabama
...           ...      ...   ...          ...      ...
2539          USA    total  2010  309326295.0      NaN
2540          USA  under18  2011   73902222.0      NaN
2541          USA    total  2011  311582564.0      NaN
2542          USA  under18  2012   73708179.0      NaN
2543          USA    total  2012  313873685.0      NaN

[2544 rows x 5 columns]

In [229]:
merged=merged.drop('abbreviation',axis=1)

In [233]:
merged.isnull().sum()

state/region     0
ages             0
year             0
population      20
state           96
dtype: int64

In [244]:
merged[merged['state'].isnull()].unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [251]:
merged.loc[merged['state'].isnull(), 'state/region'].unique()

array(['PR', 'USA'], dtype=object)

In [252]:
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

In [254]:
final = pd.merge(merged, areas, on='state', how='left')
final.head()


state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [255]:
 final.isnull().any()


state/region     False
ages             False
year             False
population        True
state            False
area (sq. mi)     True
dtype: bool

In [256]:
 final['state'][final['area (sq. mi)'].isnull()].unique()


array(['United States'], dtype=object)

In [258]:
final.dropna(inplace=True)
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [259]:
data2010 = final.query("year == 2010 & ages == 'total'")
data2010.head()


state/region   ages  year  population       state  area (sq. mi)
3             AL  total  2010   4785570.0     Alabama        52423.0
91            AK  total  2010    713868.0      Alaska       656425.0
101           AZ  total  2010   6408790.0     Arizona       114006.0
189           AR  total  2010   2922280.0    Arkansas        53182.0
197           CA  total  2010  37333601.0  California       163707.0

In [278]:
final.groupby('state'),'alabama'.count()

TypeError: count() takes at least 1 argument (0 given)

In [268]:
import seaborn as sns

In [269]:
sns

<module 'seaborn' from 'C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\seaborn\\__init__.py'>

In [271]:
planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [272]:
 rng = np.random.RandomState(42)

In [273]:
ser = pd.Series(rng.rand(5))
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [274]:
planets.dropna().describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [279]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
'data': range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [282]:
df.groupby('key').count()

data
key      
A       2
B       2
C       2

In [283]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [305]:
nama=final.groupby('state')['state'].sum()

In [306]:
nama.shape

(52,)

In [291]:
array(nama)

NameError: name 'array' is not defined

In [292]:
import numpy as np

In [293]:
array(nama)

NameError: name 'array' is not defined

In [295]:
nama.columns['state','jumlah']

AttributeError: 'Series' object has no attribute 'columns'

In [298]:
pd.Series(nama)

(52,)

In [299]:
pd.Series(nama).array

<PandasArray>
[48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
 48, 28, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48]
Length: 52, dtype: int64

In [304]:
nama

state
Alabama                 48
Alaska                  48
Arizona                 48
Arkansas                48
California              48
Colorado                48
Connecticut             48
Delaware                48
District of Columbia    48
Florida                 48
Georgia                 48
Hawaii                  48
Idaho                   48
Illinois                48
Indiana                 48
Iowa                    48
Kansas                  48
Kentucky                48
Louisiana               48
Maine                   48
Maryland                48
Massachusetts           48
Michigan                48
Minnesota               48
Mississippi             48
Missouri                48
Montana                 48
Nebraska                48
Nevada                  48
New Hampshire           48
New Jersey              48
New Mexico              48
New York                48
North Carolina          48
North Dakota            48
Ohio                    48
Oklahoma              

In [307]:
nama

state
Alabama                 AlabamaAlabamaAlabamaAlabamaAlabamaAlabamaAlab...
Alaska                  AlaskaAlaskaAlaskaAlaskaAlaskaAlaskaAlaskaAlas...
Arizona                 ArizonaArizonaArizonaArizonaArizonaArizonaAriz...
Arkansas                ArkansasArkansasArkansasArkansasArkansasArkans...
California              CaliforniaCaliforniaCaliforniaCaliforniaCalifo...
Colorado                ColoradoColoradoColoradoColoradoColoradoColora...
Connecticut             ConnecticutConnecticutConnecticutConnecticutCo...
Delaware                DelawareDelawareDelawareDelawareDelawareDelawa...
District of Columbia    District of ColumbiaDistrict of ColumbiaDistri...
Florida                 FloridaFloridaFloridaFloridaFloridaFloridaFlor...
Georgia                 GeorgiaGeorgiaGeorgiaGeorgiaGeorgiaGeorgiaGeor...
Hawaii                  HawaiiHawaiiHawaiiHawaiiHawaiiHawaiiHawaiiHawa...
Idaho                   IdahoIdahoIdahoIdahoIdahoIdahoIdahoIdahoIdahoI...
Illinois                Illinois

In [308]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [311]:
planets.groupby('method')['year'].describe().stack()

method                          
Astrometry                 count       2.00000
                           mean     2011.50000
                           std         2.12132
                           min      2010.00000
                           25%      2010.75000
                                       ...    
Transit Timing Variations  min      2011.00000
                           25%      2011.75000
                           50%      2012.50000
                           75%      2013.25000
                           max      2014.00000
Length: 79, dtype: float64

In [312]:
titanic=sns.load_dataset('titanic')

In [330]:
titanic.groupby(['sex','class'])['survived'].aggregate('mean').unstack()

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [323]:
data

name  apa
a     1      0.781368
      2      0.462466
c     1      0.982006
      2      0.925058
b     1      0.646734
      2      0.407382
dtype: float64

In [338]:
titanic.pivot_table('survived',index='sex',columns='class',aggfunc='sum',margins='Yes')

class   First  Second  Third  All
sex                              
female     91      70     72  233
male       45      17     47  109
All       136      87    119  342

In [333]:
titanic['age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [336]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]